# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20170718_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
    ]
