# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170718_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small')], default='S', max_length=2),
        ),
    ]
